list1 = ["一","二","三",6,7,8,[4,5]]
#print(list1[3])
# print(list1[1:5:1])
# print(list1[6][1])
# list1.append("kx")
# print(list1)
# list1.insert(4,"king")
# print(list1)
# list1.extend(["q","w","e"])
# print(list1)
# list1.pop()
# print(list1)
# list1.remove("三")
# print(list1)
# list1.clear()
# print(list1)
# list1[2]="四"
# print(list1)
# print(len(list1))
# list1.append("三")
# print(list1)
# print(list1.count("三"))
tuple1 = ("无","六","七",6,7,8,)
# print(tuple1)
# list1=list(tuple1)
# list1[-1]="十"
# print(list1)
# tuple2=tuple(list1)
# print(tuple2)
dict1={"name":"张三","height":"175","weight":"75"}
# print(dict1["height"])
# print(dict1.get("weight"))
# dict1["weight"]="70"
# print(dict1)